// 메디컬 칼럼 글 페이지 생성기
//
//   node tools/build-columns.mjs
//
// columns-data.js 를 읽어서 아래를 다시 만듭니다. 칼럼을 추가·수정한 뒤 실행하고, 결과 파일을 함께 커밋합니다.
//   - column-<slug>.html  : 글마다 하나씩, 본문이 HTML 에 그대로 들어간 정적 페이지 (검색엔진 색인용)
//   - sitemap.xml         : <!-- columns:start --> ~ <!-- columns:end --> 사이
//   - index.html          : 홈 칼럼 미리보기 (최신 3편) <!-- columns:latest:start --> ~ end 사이
//   - column.html         : 자바스크립트 없이 읽는 크롤러용 링크 목록 <!-- columns:noscript:start --> ~ end 사이
// columns-data.js 에서 빠진 글의 페이지는 지웁니다 (이 생성기가 만든 파일만).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// TODO: 도메인 확정 후 실제 도메인으로 교체 (sitemap.xml · 각 페이지 canonical 과 함께)
const SITE = 'https://all-detail-clinic.vercel.app';
const OG_IMAGE = SITE + '/images/int-reception.jpg';
const AUTHOR = { name: '조주형', title: '대표원장' };
const CLINIC = '올디테일의원';
const GENERATED = '<!-- generated by tools/build-columns.mjs from columns-data.js — 직접 고치지 말고 columns-data.js 를 수정한 뒤 다시 생성하세요 -->';

const CAT_KO = {
  LIFTING: '리프팅',
  COMFORT: '통증과 마취',
  PIGMENT: '색소',
  BOOSTER: '스킨부스터',
  DESIGN: '디자인',
  INSIGHT: '인사이트'
};

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const EOL = '\r\n';

const read = (f) => fs.readFileSync(path.join(ROOT, f), 'utf8');
const write = (f, s) => fs.writeFileSync(path.join(ROOT, f), s.replace(/\r?\n/g, EOL), 'utf8');

// columns-data.js is a browser ES module; load it the same way regardless of Node's module settings
const src = read('columns-data.js');
const { POSTS } = await import('data:text/javascript;charset=utf-8,' + encodeURIComponent(src));

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
const isoDate = (d) => d.replace(/\./g, '-');
const fileOf = (p) => 'column-' + p.slug + '.html';
const urlOf = (p) => SITE + '/column-' + p.slug;
const byDateDesc = (list) => list.slice().sort((a, b) => b.date.localeCompare(a.date));
const jsonLd = (o) => JSON.stringify(o, null, 2).replace(/</g, '\\u003c');

// ---- checks ----
const seen = new Set();
for (const p of POSTS) {
  for (const k of ['cat', 'date', 'slug', 'title', 'excerpt', 'body']) {
    if (!p[k]) throw new Error(`columns-data.js: "${p.title || p.slug}" 에 ${k} 가 없습니다`);
  }
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug)) throw new Error(`slug 는 영문 소문자 · 숫자 · 하이픈만: ${p.slug}`);
  if (seen.has(p.slug)) throw new Error(`slug 중복: ${p.slug}`);
  if (!CAT_KO[p.cat]) throw new Error(`알 수 없는 cat: ${p.cat} (${p.slug})`);
  if (!/^\d{4}\.\d{2}\.\d{2}$/.test(p.date)) throw new Error(`date 형식은 YYYY.MM.DD: ${p.date} (${p.slug})`);
  seen.add(p.slug);
}

// ---- pieces ----
const ROW_STYLE = 'display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 20px; align-items: baseline; padding: clamp(20px, 3vh, 32px) 4px; border-bottom: 1px solid #E4E9E6; color: #121614;';

function row(p, indent) {
  return [
    `<a href="${fileOf(p)}" style="${ROW_STYLE}" style-hover="background: #F2F5F3; color: #121614;">`,
    `  <span>`,
    `    <span style="display: block; margin-bottom: 10px; font-size: 10.5px; letter-spacing: 0.18em; color: #2C7A6B;">${esc(p.cat)}</span>`,
    `    <span style="display: block; font-size: clamp(19px, 2.1vw, 28px); font-weight: 600; letter-spacing: -0.04em; line-height: 1.4;">${esc(p.title)}</span>`,
    `    <span style="display: block; margin-top: 10px; font-size: 13.5px; line-height: 1.85; color: #6A736F; max-width: 680px;">${esc(p.excerpt)}</span>`,
    `  </span>`,
    `  <span style="font-family: 'Newsreader', serif; font-size: 13px; color: #8B948F; white-space: nowrap;">${esc(p.date)}</span>`,
    `</a>`
  ].map((l) => indent + l).join('\n');
}

function block([kind, text]) {
  const inner = {
    h: `<h2 style="margin: 44px 0 16px; font-size: clamp(18px, 1.8vw, 23px); font-weight: 600; letter-spacing: -0.035em; line-height: 1.5;">${esc(text)}</h2>`,
    b: `<p style="margin: 0; font-size: 15.5px; line-height: 2.05; color: #37413D;">${esc(text)}</p>`,
    n: `<p style="margin: 0; padding: 18px 20px; background: #F1F5F3; font-size: 14px; line-height: 1.95; color: #4C5652;">${esc(text)}</p>`
  }[kind];
  if (!inner) throw new Error(`알 수 없는 본문 종류: ${kind}`);
  return `            <div style="margin-bottom: 30px; max-width: 720px;">\n              ${inner}\n            </div>`;
}

function related(p) {
  const others = byDateDesc(POSTS.filter((x) => x !== p));
  const same = others.filter((x) => x.cat === p.cat);
  return [...same, ...others.filter((x) => x.cat !== p.cat)].slice(0, 3);
}

function page(p) {
  const url = urlOf(p);
  const cat = CAT_KO[p.cat];
  const title = `${p.title} — ${CLINIC} 메디컬 칼럼`;
  const article = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: p.title,
    description: p.excerpt,
    datePublished: isoDate(p.date),
    dateModified: isoDate(p.date),
    inLanguage: 'ko-KR',
    articleSection: cat,
    mainEntityOfPage: url,
    url,
    image: OG_IMAGE,
    author: {
      '@type': 'Person',
      name: AUTHOR.name,
      jobTitle: AUTHOR.title,
      worksFor: { '@type': 'MedicalClinic', name: CLINIC, url: SITE + '/' }
    },
    publisher: {
      '@type': 'MedicalClinic',
      name: CLINIC,
      url: SITE + '/',
      logo: { '@type': 'ImageObject', url: SITE + '/images/symbol.svg' }
    }
  };
  const crumbs = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: '홈', item: SITE + '/' },
      { '@type': 'ListItem', position: 2, name: '메디컬 칼럼', item: SITE + '/column' },
      { '@type': 'ListItem', position: 3, name: p.title, item: url }
    ]
  };

  return `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
${GENERATED}
<title>${esc(title)}</title>
<meta name="description" content="${esc(p.excerpt)}">
<meta name="author" content="${esc(CLINIC + ' ' + AUTHOR.title + ' ' + AUTHOR.name)}">
<link rel="canonical" href="${url}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="ALL DETAIL CLINIC">
<meta property="og:locale" content="ko_KR">
<meta property="og:title" content="${esc(p.title)}">
<meta property="og:description" content="${esc(p.excerpt)}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${OG_IMAGE}">
<meta property="og:image:width" content="938">
<meta property="og:image:height" content="525">
<meta property="article:published_time" content="${isoDate(p.date)}">
<meta property="article:section" content="${esc(cat)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="${OG_IMAGE}">
<link rel="icon" type="image/svg+xml" href="images/symbol.svg">
<script type="application/ld+json">
${jsonLd(article)}
</script>
<script type="application/ld+json">
${jsonLd(crumbs)}
</script>
<script src="./support.js"></script>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,200..500;1,6..72,200..400&display=swap" />
<style>
  @font-face {
    font-family: 'SUIT Variable';
    font-weight: 100 900;
    font-style: normal;
    font-display: swap;
    src: url('https://cdn.jsdelivr.net/gh/sun-typeface/SUIT/fonts/variable/woff2/SUIT-Variable.woff2') format('woff2-variations');
  }
  *, *::before, *::after { box-sizing: border-box; }
  html { scroll-behavior: smooth; overflow-x: hidden; scroll-padding-top: 118px; }
  body { margin: 0; background: #F9FAF9; color: #121614; -webkit-font-smoothing: antialiased; }
  a { color: #121614; text-decoration: none; }
  a:hover { color: #2C7A6B; }
  ::selection { background: #D6E7E2; color: #121614; }
  @media (max-width: 899px) {
    [data-sticky-col] { position: static !important; top: auto !important; }
    [data-article] { grid-template-columns: 1fr !important; }
    [data-article-aside] { position: static !important; }
    p > a { display: inline-block !important; padding: 10px 0 !important; }
  }
</style>
</head>
<body>
<x-dc>
<div style="font-family: 'SUIT Variable', system-ui, sans-serif; background: #F9FAF9; color: #121614; word-break: keep-all; text-wrap: pretty;">

  <dc-import name="Site Header" active="column" hint-size="100%,92px"></dc-import>

  <main style="padding: 92px 0 0;">
    <nav aria-label="breadcrumb" style="padding: clamp(28px, 5vh, 48px) clamp(16px, 3vw, 40px) 0; font-size: 11px; letter-spacing: 0.16em; color: #8B948F;">
      <a href="index.html" style="color: #8B948F;">HOME</a>&nbsp; / &nbsp;<a href="column.html" style="color: #8B948F;">MEDICAL COLUMN</a>&nbsp; / &nbsp;<span style="color: #2C7A6B;">${esc(p.cat)}</span>
    </nav>

    <section style="padding: clamp(28px, 5vh, 56px) clamp(16px, 3vw, 40px) clamp(56px, 9vh, 110px);">
      <div data-article style="max-width: 1560px; margin: 0 auto; display: grid; grid-template-columns: minmax(0, 280px) minmax(0, 1fr); gap: clamp(28px, 5vw, 80px); align-items: start;">
        <aside data-article-aside data-sticky-col style="position: sticky; top: 130px;">
          <a href="column.html" style="display: inline-block; margin-bottom: 28px; font-size: 11px; letter-spacing: 0.16em; color: #8B948F;">← ALL COLUMNS</a>
          <p style="margin: 0 0 12px; font-size: 10.5px; letter-spacing: 0.18em; color: #2C7A6B;">${esc(p.cat)}</p>
          <p style="margin: 0 0 26px; font-family: 'Newsreader', serif; font-size: 14px; color: #8B948F;"><time datetime="${isoDate(p.date)}">${esc(p.date)}</time></p>
          <p style="margin: 0; padding-top: 18px; border-top: 1px solid #E4E9E6; font-size: 12.5px; line-height: 1.9; color: #8B948F;">글 · ${esc(CLINIC)} ${esc(AUTHOR.title)} ${esc(AUTHOR.name)}</p>
        </aside>

        <article>
          <h1 style="margin: 0 0 clamp(22px, 3.4vh, 36px); font-size: clamp(26px, 3.4vw, 50px); font-weight: 600; letter-spacing: -0.045em; line-height: 1.28;">${esc(p.title)}</h1>
          <p style="margin: 0 0 clamp(30px, 4vh, 48px); padding-bottom: clamp(26px, 4vh, 40px); border-bottom: 1px solid #E4E9E6; font-size: clamp(16px, 1.6vw, 20px); line-height: 1.85; letter-spacing: -0.02em; color: #37413D;">${esc(p.excerpt)}</p>
${p.body.map(block).join('\n')}

          <div style="margin-top: clamp(40px, 6vh, 72px); padding-top: 26px; border-top: 1px solid #121614; display: flex; flex-wrap: wrap; gap: 12px;">
            <a href="reserve.html" style="display: inline-flex; align-items: center; height: 54px; padding: 0 28px; background: #2C7A6B; color: #F9FAF9; font-size: 12px; letter-spacing: 0.2em;" style-hover="background: #12463C; color: #F9FAF9;">RESERVE</a>
            <a href="column.html" style="display: inline-flex; align-items: center; height: 54px; padding: 0 28px; border: 1px solid #121614; font-size: 12px; letter-spacing: 0.2em;" style-hover="background: #12463C; color: #F9FAF9;">ALL COLUMNS</a>
          </div>
        </article>
      </div>
    </section>

    <section style="padding: 0 clamp(16px, 3vw, 40px) clamp(56px, 9vh, 110px);">
      <div style="max-width: 1560px; margin: 0 auto;">
        <p style="margin: 0 0 clamp(18px, 3vh, 28px); font-family: 'Newsreader', serif; font-size: clamp(20px, 2vw, 28px); letter-spacing: -0.02em; color: #2C7A6B;">More columns</p>
        <div style="border-top: 1px solid #121614;">
${related(p).map((x) => row(x, '          ')).join('\n')}
        </div>
      </div>
    </section>
  </main>

  <dc-import name="Site Footer" hint-size="100%,420px"></dc-import>
  <dc-import name="Consult Dock" hint-size="62px,62px" style="position: fixed; right: 0px; bottom: 0px; width: 62px; height: 62px; z-index: 150;"></dc-import>
</div>
</x-dc>
<script type="text/x-dc" data-dc-script data-props="{&quot;$preview&quot;:{&quot;width&quot;:1440}}">
class Component extends DCLogic {
  renderVals() { return {}; }
}
</script>
</body>
</html>
`;
}

function replaceBetween(file, start, end, body) {
  const s = read(file);
  const a = s.indexOf(start);
  const b = s.indexOf(end);
  if (a < 0 || b < a) throw new Error(`${file}: ${start} / ${end} 표시를 찾을 수 없습니다`);
  write(file, s.slice(0, a + start.length) + '\n' + body + (body ? '\n' : '') + s.slice(b));
}

// ---- 1) article pages ----
const keep = new Set();
for (const p of POSTS) {
  write(fileOf(p), page(p));
  keep.add(fileOf(p));
}
const removed = [];
for (const f of fs.readdirSync(ROOT)) {
  if (!/^column-.+\.html$/.test(f) || keep.has(f)) continue;
  if (read(f).includes('generated by tools/build-columns.mjs')) {
    fs.unlinkSync(path.join(ROOT, f));
    removed.push(f);
  }
}

// ---- 2) sitemap ----
replaceBetween('sitemap.xml', '<!-- columns:start -->', '  <!-- columns:end -->',
  byDateDesc(POSTS).map((p) =>
    `  <url><loc>${urlOf(p)}</loc><lastmod>${isoDate(p.date)}</lastmod><changefreq>yearly</changefreq><priority>0.7</priority></url>`
  ).join('\n'));

// ---- 3) home preview: latest 3 ----
replaceBetween('index.html', '<!-- columns:latest:start -->', '<!-- columns:latest:end -->',
  byDateDesc(POSTS).slice(0, 3).map((p) => row(p, '        ')).join('\n'));

// ---- 4) column list: plain links for crawlers without JavaScript ----
replaceBetween('column.html', '<!-- columns:noscript:start -->', '<!-- columns:noscript:end -->',
  '<ul>\n' + byDateDesc(POSTS).map((p) =>
    `  <li><a href="${fileOf(p)}">${esc(p.title)}</a> — ${esc(p.excerpt)}</li>`
  ).join('\n') + '\n</ul>');

console.log(`칼럼 ${POSTS.length}편 생성: ${[...keep].join(', ')}`);
if (removed.length) console.log(`삭제: ${removed.join(', ')}`);
